user:
  outputs:
    default:
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: dbt-user-prav@cobalt-psyche-472916-h3.iam.gserviceaccount.com
        client_id: '103677787736681584026'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/dbt-user-prav%40cobalt-psyche-472916-h3.iam.gserviceaccount.com
        private_key: '-----BEGIN PRIVATE KEY-----

          MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDKZoHt5TpmI8GN

          DI9t1WDhEgmv3HNvZNzsEmfUymHzhiPrihF9kZ71dnT4zzGMjKrQt0m6SDk5wi4Q

          ApOcNvzdU7eilN8HpH666lDZqXBL9Y+KY84Yc7EUHK4utA3jkorB3DnFLtYd4WSk

          hBVlI2nxQzESuKFBX0oJ87u5l/yEH9v+aOjz0fLRL6Q06M1tkUyNlBeQCc4XYJk4

          V+i5GAhH/OvG4oVVY3Ml9WosK7IxRWlHY8vUWGgeZen072sUj9F8UG9SrIVraD/2

          N9ytcXn33RNij5cxLb6/Jh6PavFH39hZwQWg37vqxZqVONrAKdHbAZ96rOMSNsbV

          swQOFydbAgMBAAECggEAS7tzXlppMZKrd2V9vXEb4Nto+H6aStIIv+RbKYnYgNBu

          XFG7HasBOYNrXTXZqmdv+sy6L5Oapfv8VE1Cgi8pCn+qtJDTqv5n1PSb7/WwaRum

          6/dQRGH1njrlCeChWceZV9RZYWiXAXM2v0AU6VUI7RdhI0omPFm1UGf8lANEnwLK

          K7mupEe9zZPLtVX8cQxu37tR1gvJZoe0zDFEHmkxt0kgyPrSI6A9xvdHTpKh3NuE

          IFyfVWm9NMItbcqxa2zsLHbSu4Qiows4cryAmzxfuVAq8I/GPXnwfGYbfAaecm3h

          12uKC2tCZuPCAr4mRyZw4sTMov3AnyhJmQO5nPqngQKBgQDwSub8NJq9EGPV+cPC

          Dy4CFIF5T3Ut3nn0xBsaSjE6Di4Y2S/cRK6YNro4DNETL8t8bPERaZFfvaL5cqgK

          6Qdw5TywqLPZ9SS9Vj9iY8HyO8yP+/QTgC/hGZDvI4h9K43+2KMLUX/GkjgCzc+z

          WwCOC/xwFnJCV35DHP27UqUP4QKBgQDXoYLcS2UJ+f0L1XH8k065xz4Sg6tefb/A

          XuCfFSDOg1tHFBP3e5/7c6LbtHlUc5EXQqCqZwINQi4MQfg1vgSHfpimO1LIaLxH

          6boY86HYJMu2sYO+2ZmP/lWGlzqPE1vudBhN4Skm/r/8ZADPUCYx/G+SJwHRzpFA

          9QOt0m5OuwKBgQCKVnT4ycg0BJWVgL+En3ybUfbgQjByAd0wXx5DWmdQxw0e3RrC

          sv/ZPdijoC1V4HRD4+w9XAuHlQOYnLvF3DaedjskcVtppcpK/rZrDIeBz4+LbUAt

          YeUusKtSIaDYfxS2nT3wrDDlvxRj+N0UotWE8b2ZQjLxorFcLfqdt4yzwQKBgCyN

          hYFI3q6KBXu9dVjPgvOltDCVHgJfDxCLSfP0pJumzmRIRLvcwjhtMxgcGPmXC0J4

          FMRAlk7w/pyvwL4x7bOlN5sZJMidw1FEfJwNMsJ7D9BGq0bypOT4kulFM+c+A7+o

          IyFsRVl2R2q5quUq1Ul8s/zJrHmSKbb3KPRwRzRjAoGBAIxRwcrl/VObZ4G5+duV

          jjy+L7w5Dwr71Fy4AXq4GUJx+QSnkJjefzGQ8hAcoz6rXzaQiWfbInc93jcJ0J+x

          5M6sjnItBMFrgG12UffT+GGYx+qK1ZnC3ohkPsrvOGIAez1LJv8h/bkBHJ+LY4Zv

          NhHOorb4AdCXChsgAy8OsWfz

          -----END PRIVATE KEY-----

          '
        private_key_id: ec48475146e56789299324fb0ea7937bc3551dcf
        project_id: cobalt-psyche-472916-h3
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      method: service-account-json
      project: cobalt-psyche-472916-h3
      schema: dbt_ps
      scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/userinfo.email
      target_name: default
      threads: 6
      type: bigquery
  target: default
